Update patch set 1
Patch Set 1: Verified-1

wallaby7: build failed:
[  7%] Generating old_timestamp, host_driver.o, mem_alloc.o, mm.o, mikc.o, ../../ikc/linux.o, ../../ikc/master.o, ../../ikc/queue.o, .host_driver.o.cmd, .mem_alloc.o.cmd, .mm.o.cmd, .mikc.o.cmd, ../../ikc/.linux.o.cmd, ../../ikc/.master.o.cmd, ../../ikc/.queue.o.cmd, ihk.o, .ihk.o.cmd, ihk.mod.c, ihk.mod.o, .ihk.mod.o.cmd, .ihk.ko.cmd, .tmp_versions/ihk.mod, .tmp_versions, modules.order
[ 14%] Building kmod ihk
/work/mcktest/git/ihk/linux/core/host_driver.c: In function ‘__ihk_device_create_os’:
/work/mcktest/git/ihk/linux/core/host_driver.c:1629:8: error: ‘__GFP_ATOMIC’ undeclared (first use in this function)
        __GFP_ATOMIC | __GFP_HIGH |
        ^
/work/mcktest/git/ihk/linux/core/host_driver.c:1629:8: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [/tmp/build-ihk/linux/core/host_driver.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-ihk/linux/core] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [linux/core/ihk.ko] Error 2
make[2]: Target `linux/core/CMakeFiles/ihk_ko.dir/build' not remade because of errors.
make[1]: *** [linux/core/CMakeFiles/ihk_ko.dir/all] Error 2
[ 28%] Built target ihklib
[ 42%] Built target ihkosctl
[ 57%] Built target ihkconfig
[ 71%] Built target ihkmond
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1