Update patch set 1
Patch Set 1: Build-arm64-1

apollo15: build report: build failed:
[ 10%] Generating kmod_always_rebuild
[ 20%] Building kmod ihk
[ 30%] Built target ihk_ko
[ 40%] Building C object linux/user/CMakeFiles/ihklib.dir/ihklib.c.o
/tmp/ihk/linux/user/ihklib.c:100:2: error: unknown field ‘balanced_enable’ specified in initializer
  .balanced_enable = 0,
  ^
/tmp/ihk/linux/user/ihklib.c:101:2: error: unknown field ‘balanced_best_effort’ specified in initializer
  .balanced_best_effort = 0,
  ^
/tmp/ihk/linux/user/ihklib.c:102:2: error: unknown field ‘balanced_variance_limit’ specified in initializer
  .balanced_variance_limit = 0,
  ^
/tmp/ihk/linux/user/ihklib.c:103:2: error: initialized field overwritten [-Werror=override-init]
  .min_chunk_size = PAGE_SIZE,
  ^
/tmp/ihk/linux/user/ihklib.c:103:2: error: (near initialization for ‘reserve_mem_conf.min_chunk_size’) [-Werror=override-init]
/tmp/ihk/linux/user/ihklib.c: In function ‘ihk_reserve_mem_conf’:
/tmp/ihk/linux/user/ihklib.c:994:7: error: ‘IHK_RESERVE_MEM_BALANCED_ENABLE’ undeclared (first use in this function)
  case IHK_RESERVE_MEM_BALANCED_ENABLE:
       ^
/tmp/ihk/linux/user/ihklib.c:994:7: note: each undeclared identifier is reported only once for each function it appears in
/tmp/ihk/linux/user/ihklib.c:995:19: error: ‘struct ihklib_reserve_mem_conf’ has no member named ‘balanced_enable’
   reserve_mem_conf.balanced_enable = 1;
                   ^
/tmp/ihk/linux/user/ihklib.c:997:7: error: ‘IHK_RESERVE_MEM_BALANCED_BEST_EFFORT’ undeclared (first use in this function)
  case IHK_RESERVE_MEM_BALANCED_BEST_EFFORT:
       ^
/tmp/ihk/linux/user/ihklib.c:998:19: error: ‘struct ihklib_reserve_mem_conf’ has no member named ‘balanced_best_effort’
   reserve_mem_conf.balanced_best_effort = *((int *)value);
                   ^
/tmp/ihk/linux/user/ihklib.c:1000:7: error: ‘IHK_RESERVE_MEM_BALANCED_VARIANCE_LIMIT’ undeclared (first use in this function)
  case IHK_RESERVE_MEM_BALANCED_VARIANCE_LIMIT:
       ^
/tmp/ihk/linux/user/ihklib.c:1001:19: error: ‘struct ihklib_reserve_mem_conf’ has no member named ‘balanced_variance_limit’
   reserve_mem_conf.balanced_variance_limit = *((int *)value);
                   ^
/tmp/ihk/linux/user/ihklib.c: In function ‘ihk_reserve_mem’:
/tmp/ihk/linux/user/ihklib.c:1089:23: error: ‘struct ihklib_reserve_mem_conf’ has no member named ‘balanced_enable’
   if (reserve_mem_conf.balanced_enable) {
                       ^
/tmp/ihk/linux/user/ihklib.c:1120:22: error: ‘struct ihklib_reserve_mem_conf’ has no member named ‘balanced_enable’
  if (reserve_mem_conf.balanced_enable) {
                      ^
/tmp/ihk/linux/user/ihklib.c:1167:24: error: ‘struct ihklib_reserve_mem_conf’ has no member named ‘balanced_best_effort’
    if (reserve_mem_conf.balanced_best_effort) {
                        ^
cc1: all warnings being treated as errors
make[2]: *** [linux/user/CMakeFiles/ihklib.dir/ihklib.c.o] Error 1
make[2]: Target `linux/user/CMakeFiles/ihklib.dir/build' not remade because of errors.
make[1]: *** [linux/user/CMakeFiles/ihklib.dir/all] Error 2
[ 50%] Generating kmod_always_rebuild
[ 60%] Building kmod ihk-smp-arm64
[ 70%] Built target ihk-smp-arm64_ko
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1