Update patch set 5
Patch Set 5: Verified-1

build failed:
[ 10%] Generating old_timestamp, host_driver.o, mem_alloc.o, mm.o, mikc.o, ../../ikc/linux.o, ../../ikc/master.o, ../../ikc/queue.o, .host_driver.o.cmd, .mem_alloc.o.cmd, .mm.o.cmd, .mikc.o.cmd, ../../ikc/.linux.o.cmd, ../../ikc/.master.o.cmd, ../../ikc/.queue.o.cmd, ihk.o, .ihk.o.cmd, ihk.mod.c, ihk.mod.o, .ihk.mod.o.cmd, .ihk.ko.cmd, .tmp_versions/ihk.mod, .tmp_versions, modules.order
[ 20%] Building kmod ihk
/work/mcktest/git/ihk/linux/core/host_driver.c:792:12: error: conflicting types for ‘__ihk_os_status’
 static int __ihk_os_status(struct ihk_host_linux_os_data *data,
            ^
/work/mcktest/git/ihk/linux/core/host_driver.c:360:12: note: previous declaration of ‘__ihk_os_status’ was here
 static int __ihk_os_status(struct ihk_host_linux_os_data *data);
            ^
/work/mcktest/git/ihk/linux/core/host_driver.c:360:12: error: ‘__ihk_os_status’ used but never defined [-Werror]
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-ihk/linux/core/host_driver.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-ihk/linux/core] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [linux/core/ihk.ko] Error 2
make[2]: Target `linux/core/CMakeFiles/ihk_ko.dir/build' not remade because of errors.
make[1]: *** [linux/core/CMakeFiles/ihk_ko.dir/all] Error 2
[ 30%] Building C object linux/user/CMakeFiles/ihklib.dir/ihklib.c.o
/work/mcktest/git/ihk/linux/user/ihklib.c: In function ‘ihk_os_assign_mem’:
/work/mcktest/git/ihk/linux/user/ihklib.c:2116:7: error: unused variable ‘errno_save’ [-Werror=unused-variable]
   int errno_save = errno;
       ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2787:12: error: invalid storage class for function ‘get_meminfo_path’
 static int get_meminfo_path(char *path, int os_index, int node)
            ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2866:12: error: invalid storage class for function ‘ihklib_os_query_mem’
 static int ihklib_os_query_mem(int index, unsigned long *result,
            ^
/work/mcktest/git/ihk/linux/user/ihklib.c:3793:1: error: expected declaration or statement at end of input
 }
 ^
/work/mcktest/git/ihk/linux/user/ihklib.c:3793:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
make[2]: *** [linux/user/CMakeFiles/ihklib.dir/ihklib.c.o] Error 1
make[2]: Target `linux/user/CMakeFiles/ihklib.dir/build' not remade because of errors.
make[1]: *** [linux/user/CMakeFiles/ihklib.dir/all] Error 2
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 5
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1