Update patch set 3
Patch Set 3:

MCKERNEL : mckernel-development@{1586421227}-?
IHK      : ihk-development@{1586421227}-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/ihk/+/489197/3 // 4ea2c18dd39786e899bc508f79ab1649908222a8
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3
START : 20200413093951
END   : 20200413094005

+++ dirname /work/mcktest/bin/autobuild.sh
++ cd /work/mcktest/bin/..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ pwd
+ CWD=/
++ dirname /work/mcktest/bin/autobuild.sh
+ cd /work/mcktest/bin
+ . ./config.sh
++ export NODETYPE=wallaby
++ NODETYPE=wallaby
++ export WGETSSHPROXY=ofp05
++ WGETSSHPROXY=ofp05
++ export 'WGETPROXYOPTS=-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ WGETPROXYOPTS='-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ MCKERNELBRANCH='development@{1586421227}'
++ IHKBRANCH=refs-changes-97-489197-3
++ REFBRANCH=development
++ export 'WORKDIR=/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3'
++ WORKDIR='/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3'
++ SRC='/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src'
++ MCKBUILD='/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/build'
++ MCKINSTALL='/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck'
++ BUILDID_DIR=/work/mcktest/buildids
++ GITS=/work/mcktest/git
++ LTPINSTALL=/work/mcktest/ltp/install
++ STRESS_TEST_DIR=/work/mcktest/stress_test/install
++ MCKBUILDSCRIPT=/work/mcktest/bin/config_and_build_smp_x86.sh
++ MPICH=/usr/lib64/mpich-3.2
++ export LTPDIR=/work/mcktest/ltp/install
++ LTPDIR=/work/mcktest/ltp/install
++ export LTPROOT=/work/mcktest/ltp/install
++ LTPROOT=/work/mcktest/ltp/install
++ export 'MAIL_TO=mckernel@www.pccluster.org toshi@metahack.jp'
++ MAIL_TO='mckernel@www.pccluster.org toshi@metahack.jp'
++ export 'MCKERNELCONFIGOPTION=--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ MCKERNELCONFIGOPTION='--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ export IHKCONFIGOPTION=--enable-rusage
++ IHKCONFIGOPTION=--enable-rusage
++ MCREBOOTOPTION='-k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O'
++ export 'PATH=/work/mcktest/bin:/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck/bin:/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin'
++ PATH='/work/mcktest/bin:/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck/bin:/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin'
++ export DATADIR=/work/mcktest/data
++ DATADIR=/work/mcktest/data
++ export BINDIR=/work/mcktest/bin
++ BINDIR=/work/mcktest/bin
++ export LOGDIR=/work/mcktest/log
++ LOGDIR=/work/mcktest/log
++ STRESS_TEST_TIMEOUT=60
++ export OMP_NUM_THREADS_1=1
++ OMP_NUM_THREADS_1=1
++ export OMP_NUM_THREADS_2=2
++ OMP_NUM_THREADS_2=2
++ export OMP_NUM_THREADS_4=4
++ OMP_NUM_THREADS_4=4
++ export OMP_NUM_THREADS_8=8
++ OMP_NUM_THREADS_8=8
++ export OMP_NUM_THREADS_16=16
++ OMP_NUM_THREADS_16=16
++ export OMP_NUM_THREADS_24=24
++ OMP_NUM_THREADS_24=24
++ export OMP_NUM_THREADS_32=32
++ OMP_NUM_THREADS_32=32
++ export 'MPI_HOSTS=wallaby7 wallaby13'
++ MPI_HOSTS='wallaby7 wallaby13'
++ [[ -e /work/mcktest/bin/gerrit-creds ]]
++ . /work/mcktest/bin/gerrit-creds
+++ GERRITUSER=riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg
++ export GERRITSERVER=review.gerrithub.io
++ GERRITSERVER=review.gerrithub.io
++ export 'GERRITCURL=curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ GERRITCURL='curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ export GERRIT_USER=riken-syssoft-gerrit
++ GERRIT_USER=riken-syssoft-gerrit
++ export 'GITSUDO=sudo -u mcktest'
++ GITSUDO='sudo -u mcktest'
+ export BINDIR=
+ BINDIR=
+ ./wget-postpeta.sh mckernel 'development@{1586421227}'
++ pwd
+ CWD=/work/mcktest/bin
+++ dirname ./wget-postpeta.sh
++ cd ./..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ dirname ./wget-postpeta.sh
+ cd .
+ . ./config.sh
++ export NODETYPE=wallaby
++ NODETYPE=wallaby
++ export WGETSSHPROXY=ofp05
++ WGETSSHPROXY=ofp05
++ export 'WGETPROXYOPTS=-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ WGETPROXYOPTS='-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ MCKERNELBRANCH='development@{1586421227}'
++ IHKBRANCH=refs-changes-97-489197-3
++ REFBRANCH=development
++ export 'WORKDIR=/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3'
++ WORKDIR='/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3'
++ SRC='/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src'
++ MCKBUILD='/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/build'
++ MCKINSTALL='/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck'
++ BUILDID_DIR=/work/mcktest/buildids
++ GITS=/work/mcktest/git
++ LTPINSTALL=/work/mcktest/ltp/install
++ STRESS_TEST_DIR=/work/mcktest/stress_test/install
++ MCKBUILDSCRIPT=/work/mcktest/bin/config_and_build_smp_x86.sh
++ MPICH=/usr/lib64/mpich-3.2
++ export LTPDIR=/work/mcktest/ltp/install
++ LTPDIR=/work/mcktest/ltp/install
++ export LTPROOT=/work/mcktest/ltp/install
++ LTPROOT=/work/mcktest/ltp/install
++ export 'MAIL_TO=mckernel@www.pccluster.org toshi@metahack.jp'
++ MAIL_TO='mckernel@www.pccluster.org toshi@metahack.jp'
++ export 'MCKERNELCONFIGOPTION=--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ MCKERNELCONFIGOPTION='--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ export IHKCONFIGOPTION=--enable-rusage
++ IHKCONFIGOPTION=--enable-rusage
++ MCREBOOTOPTION='-k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O'
++ export 'PATH=/work/mcktest/bin:/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck/bin:/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin'
++ PATH='/work/mcktest/bin:/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck/bin:/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin'
++ export DATADIR=/work/mcktest/data
++ DATADIR=/work/mcktest/data
++ export BINDIR=/work/mcktest/bin
++ BINDIR=/work/mcktest/bin
++ export LOGDIR=/work/mcktest/log
++ LOGDIR=/work/mcktest/log
++ STRESS_TEST_TIMEOUT=60
++ export OMP_NUM_THREADS_1=1
++ OMP_NUM_THREADS_1=1
++ export OMP_NUM_THREADS_2=2
++ OMP_NUM_THREADS_2=2
++ export OMP_NUM_THREADS_4=4
++ OMP_NUM_THREADS_4=4
++ export OMP_NUM_THREADS_8=8
++ OMP_NUM_THREADS_8=8
++ export OMP_NUM_THREADS_16=16
++ OMP_NUM_THREADS_16=16
++ export OMP_NUM_THREADS_24=24
++ OMP_NUM_THREADS_24=24
++ export OMP_NUM_THREADS_32=32
++ OMP_NUM_THREADS_32=32
++ export 'MPI_HOSTS=wallaby7 wallaby13'
++ MPI_HOSTS='wallaby7 wallaby13'
++ [[ -e /work/mcktest/bin/gerrit-creds ]]
++ . /work/mcktest/bin/gerrit-creds
+++ GERRITUSER=riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg
++ export GERRITSERVER=review.gerrithub.io
++ GERRITSERVER=review.gerrithub.io
++ export 'GERRITCURL=curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ GERRITCURL='curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ export GERRIT_USER=riken-syssoft-gerrit
++ GERRIT_USER=riken-syssoft-gerrit
++ export 'GITSUDO=sudo -u mcktest'
++ GITSUDO='sudo -u mcktest'
+ forwatchgerrit=0
+ REPO=mckernel
+ BRANCH='development@{1586421227}'
+ case "$BRANCH" in
+ remote_type=git
+ TIMESTAMP='@{1586421227}'
+ PATHSPEC=origin/development
+ '[' '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src' == '' ']'
+ '[' mckernel == '' ']'
+ DEST=mckernel
+ [[ -d /work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src ]]
+ rm -rf '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/mckernel-development@{1586421227}-270dd28b51284a3d8b79bdd7e51f509f75731898'
+ case $NODETYPE in
+ case $remote_type in
+ pushd /work/mcktest/git
/work/mcktest/git /work/mcktest/bin
+ sudo -u mcktest rm -rf mckernel
+ sudo -u mcktest git clone ssh://riken-syssoft-gerrit@review.gerrithub.io/RIKEN-SysSoft/mckernel
Cloning into 'mckernel'...
Total 31354 (delta 20330), reused 30996 (delta 20330)
+ cd mckernel
+ [[ @{1586421227} != '' ]]
+ sudo -u mcktest git checkout origin/development
Note: checking out 'origin/development'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 33eef71... spec: Update version number to 1.7.0rc3
++ sudo -u mcktest git rev-parse '@{1586421227}'
+ COMMIT=270dd28b51284a3d8b79bdd7e51f509f75731898
+ sudo -u mcktest git checkout 270dd28b51284a3d8b79bdd7e51f509f75731898
Previous HEAD position was 33eef71... spec: Update version number to 1.7.0rc3
HEAD is now at 270dd28... Merge branch 'development'
+ DEST='mckernel-development@{1586421227}-270dd28b51284a3d8b79bdd7e51f509f75731898'
+ popd
/work/mcktest/bin
+ '[' 0 -ne 0 ']'
+ '[' 0 -eq 1 ']'
+ case $remote_type in
+ mkdir '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/mckernel-development@{1586421227}-270dd28b51284a3d8b79bdd7e51f509f75731898'
+ cp -rpi /work/mcktest/git/mckernel '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/'
cp: cannot overwrite non-directory ‘/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/mckernel’ with directory ‘/work/mcktest/git/mckernel’
+ mv '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/mckernel' '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/mckernel-development@{1586421227}-270dd28b51284a3d8b79bdd7e51f509f75731898'
+ cd /work/mcktest/bin
+ exit 0
+ [[ refs-changes-97-489197-3 == \s\u\b\m\o\d\u\l\e ]]
+ case "$IHKBRANCH" in
+ ./wget-postpeta.sh ihk refs-changes-97-489197-3
++ pwd
+ CWD=/work/mcktest/bin
+++ dirname ./wget-postpeta.sh
++ cd ./..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ dirname ./wget-postpeta.sh
+ cd .
+ . ./config.sh
++ export NODETYPE=wallaby
++ NODETYPE=wallaby
++ export WGETSSHPROXY=ofp05
++ WGETSSHPROXY=ofp05
++ export 'WGETPROXYOPTS=-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ WGETPROXYOPTS='-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ MCKERNELBRANCH='development@{1586421227}'
++ IHKBRANCH=refs-changes-97-489197-3
++ REFBRANCH=development
++ export 'WORKDIR=/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3'
++ WORKDIR='/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3'
++ SRC='/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src'
++ MCKBUILD='/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/build'
++ MCKINSTALL='/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck'
++ BUILDID_DIR=/work/mcktest/buildids
++ GITS=/work/mcktest/git
++ LTPINSTALL=/work/mcktest/ltp/install
++ STRESS_TEST_DIR=/work/mcktest/stress_test/install
++ MCKBUILDSCRIPT=/work/mcktest/bin/config_and_build_smp_x86.sh
++ MPICH=/usr/lib64/mpich-3.2
++ export LTPDIR=/work/mcktest/ltp/install
++ LTPDIR=/work/mcktest/ltp/install
++ export LTPROOT=/work/mcktest/ltp/install
++ LTPROOT=/work/mcktest/ltp/install
++ export 'MAIL_TO=mckernel@www.pccluster.org toshi@metahack.jp'
++ MAIL_TO='mckernel@www.pccluster.org toshi@metahack.jp'
++ export 'MCKERNELCONFIGOPTION=--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ MCKERNELCONFIGOPTION='--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ export IHKCONFIGOPTION=--enable-rusage
++ IHKCONFIGOPTION=--enable-rusage
++ MCREBOOTOPTION='-k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O'
++ export 'PATH=/work/mcktest/bin:/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck/bin:/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin'
++ PATH='/work/mcktest/bin:/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck/bin:/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin'
++ export DATADIR=/work/mcktest/data
++ DATADIR=/work/mcktest/data
++ export BINDIR=/work/mcktest/bin
++ BINDIR=/work/mcktest/bin
++ export LOGDIR=/work/mcktest/log
++ LOGDIR=/work/mcktest/log
++ STRESS_TEST_TIMEOUT=60
++ export OMP_NUM_THREADS_1=1
++ OMP_NUM_THREADS_1=1
++ export OMP_NUM_THREADS_2=2
++ OMP_NUM_THREADS_2=2
++ export OMP_NUM_THREADS_4=4
++ OMP_NUM_THREADS_4=4
++ export OMP_NUM_THREADS_8=8
++ OMP_NUM_THREADS_8=8
++ export OMP_NUM_THREADS_16=16
++ OMP_NUM_THREADS_16=16
++ export OMP_NUM_THREADS_24=24
++ OMP_NUM_THREADS_24=24
++ export OMP_NUM_THREADS_32=32
++ OMP_NUM_THREADS_32=32
++ export 'MPI_HOSTS=wallaby7 wallaby13'
++ MPI_HOSTS='wallaby7 wallaby13'
++ [[ -e /work/mcktest/bin/gerrit-creds ]]
++ . /work/mcktest/bin/gerrit-creds
+++ GERRITUSER=riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg
++ export GERRITSERVER=review.gerrithub.io
++ GERRITSERVER=review.gerrithub.io
++ export 'GERRITCURL=curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ GERRITCURL='curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ export GERRIT_USER=riken-syssoft-gerrit
++ GERRIT_USER=riken-syssoft-gerrit
++ export 'GITSUDO=sudo -u mcktest'
++ GITSUDO='sudo -u mcktest'
+ forwatchgerrit=0
+ REPO=ihk
+ BRANCH=refs-changes-97-489197-3
+ case "$BRANCH" in
+ remote_type=gerrit-git
+ PATHSPEC=refs/changes/97/489197/3
+ '[' '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src' == '' ']'
+ '[' ihk == '' ']'
+ DEST=ihk
+ [[ -d /work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src ]]
+ rm -rf '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/ihk-refs-changes-97-489197-3-4ea2c18dd39786e899bc508f79ab1649908222a8'
+ case $NODETYPE in
+ case $remote_type in
+ pushd /work/mcktest/git
/work/mcktest/git /work/mcktest/bin
+ sudo -u mcktest rm -rf ihk
+ sudo -u mcktest git clone ssh://riken-syssoft-gerrit@review.gerrithub.io/RIKEN-SysSoft/ihk
Cloning into 'ihk'...
Total 6388 (delta 4404), reused 6258 (delta 4404)
+ cd ihk
+ sudo -u mcktest git fetch origin refs/changes/97/489197/3
Total 8 (delta 6), reused 7 (delta 6)
From ssh://review.gerrithub.io/RIKEN-SysSoft/ihk
 * branch            refs/changes/97/489197/3 -> FETCH_HEAD
++ sudo -u mcktest git rev-parse FETCH_HEAD
+ COMMIT=4ea2c18dd39786e899bc508f79ab1649908222a8
+ sudo -u mcktest git checkout 4ea2c18dd39786e899bc508f79ab1649908222a8
Note: checking out '4ea2c18dd39786e899bc508f79ab1649908222a8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 4ea2c18... smp_ihk_setup_trampoline: use __PAGE_OFFSET instead of page_offset_base
+ DEST=ihk-refs-changes-97-489197-3-4ea2c18dd39786e899bc508f79ab1649908222a8
+ popd
/work/mcktest/bin
+ '[' 0 -ne 0 ']'
+ '[' 0 -eq 1 ']'
+ case $remote_type in
+ mkdir '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/ihk-refs-changes-97-489197-3-4ea2c18dd39786e899bc508f79ab1649908222a8'
+ cp -rpi /work/mcktest/git/ihk '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/'
cp: cannot overwrite non-directory ‘/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/ihk’ with directory ‘/work/mcktest/git/ihk’
+ mv '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/ihk' '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/ihk-refs-changes-97-489197-3-4ea2c18dd39786e899bc508f79ab1649908222a8'
+ cd /work/mcktest/bin
+ exit 0
++ basename '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/ihk-refs-changes-97-489197-3-4ea2c18dd39786e899bc508f79ab1649908222a8'
+ IHKHEAD=ihk-refs-changes-97-489197-3-4ea2c18dd39786e899bc508f79ab1649908222a8
++ basename '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/mckernel-development@{1586421227}-270dd28b51284a3d8b79bdd7e51f509f75731898'
+ MCKERNELHEAD='mckernel-development@{1586421227}-270dd28b51284a3d8b79bdd7e51f509f75731898'
+ '[' -f '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck/ihk-refs-changes-97-489197-3-4ea2c18dd39786e899bc508f79ab1649908222a8' ']'
+ rm -f '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/ihk'
+ rm -f '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/mckernel'
+ '[' '!' -d '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/ihk-refs-changes-97-489197-3-4ea2c18dd39786e899bc508f79ab1649908222a8' ']'
+ ln -s ihk-refs-changes-97-489197-3-4ea2c18dd39786e899bc508f79ab1649908222a8 '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/ihk'
+ '[' '!' -d '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/mckernel-development@{1586421227}-270dd28b51284a3d8b79bdd7e51f509f75731898' ']'
+ ln -s 'mckernel-development@{1586421227}-270dd28b51284a3d8b79bdd7e51f509f75731898' '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/mckernel'
+ echo 'MCKBUILD=/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/build'
MCKBUILD=/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/build
+ echo 'MCKINSTALL=/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck'
MCKINSTALL=/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck
+ sudo rm -rf '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/build'
+ /work/mcktest/bin/config_and_build_smp_x86.sh '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src' '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/build' '/work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/mck'
/work/mcktest/bin/config_and_build_smp_x86.sh: line 36: /work/mcktest/work_development@{1586421227}_refs-changes-97-489197-3/src/ihk/configure: No such file or directory
+ error 'autobuild.sh failed'
+ echo 'ERROR: autobuild.sh failed'
ERROR: autobuild.sh failed
+ cd /
+ exit -1

Patch-set: 3
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>