Update patch set 6
Patch Set 6: Verified-1

build failed for aarch64:
[ 10%] Generating kmod_always_rebuild
[ 20%] Building kmod ihk
[ 30%] Built target ihk_ko
[ 40%] Built target ihklib
[ 50%] Built target ihkconfig
[ 60%] Built target ihkmond
[ 70%] Built target ihkosctl
[ 80%] Generating old_timestamp, arch/arm64/smp-arm64-startup.o, arch/arm64/smp-arm64-trampoline.o, arch/arm64/smp-arch-driver.o, smp-driver.o, arch/arm64/.smp-arm64-startup.o.cmd, arch/arm64/.smp-arm64-trampoline.o.cmd, arch/arm64/.smp-arch-driver.o.cmd, .smp-driver.o.cmd, ihk-smp-arm64.o, .ihk-smp-arm64.o.cmd, ihk-smp-arm64.mod.c, ihk-smp-arm64.mod.o, .ihk-smp-arm64.mod.o.cmd, .ihk-smp-arm64.ko.cmd, .tmp_versions/ihk-smp-arm64.mod, .tmp_versions, modules.order
[ 90%] Building kmod ihk-smp-arm64
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c: In function ‘smp_ihk_os_boot’:
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:473:40: error: ‘tsc_khz’ undeclared (first use in this function)
  os->param->ns_per_tsc = 1000000000L / tsc_khz;
                                        ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:473:40: note: each undeclared identifier is reported only once for each function it appears in
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c: In function ‘read_file’:
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:3790:2: warning: format ‘%p’ expects argument of type ‘void *’, but argument 5 has type ‘va_list’ [-Wformat=]
  dprintk("read_file(%p,%ld,%s,%p)\n", buf, size, fmt, ap);
  ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:3839:2: warning: format ‘%p’ expects argument of type ‘void *’, but argument 5 has type ‘va_list’ [-Wformat=]
  dprintk("read_file(%p,%ld,%s,%p): %d\n", buf, size, fmt, ap, error);
  ^
make[4]: *** [/tmp/build-aarch64-ihk/linux/driver/smp/smp-driver.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-aarch64-ihk/linux/driver/smp] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [linux/driver/smp/ihk-smp-arm64.ko] Error 2
make[2]: Target `linux/driver/smp/CMakeFiles/ihk-smp-arm64_ko.dir/build' not remade because of errors.
make[1]: *** [linux/driver/smp/CMakeFiles/ihk-smp-arm64_ko.dir/all] Error 2
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 6
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1