Update patch set 6
Patch Set 6:

MCKERNEL : mckernel-development@{1550042017}-?
IHK      : ihk-development@{1550042017}-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/ihk/+/427618/6 // 06c6ab668d14a7402822751a6139be932bad853f
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_development@{1550042017}_refs-changes-18-427618-6
START : 20190213191510
END   : 20190213191513

HEAD is now at 34a995d perfctr_stop: add flags to no 'disable_intens'
From https://review.gerrithub.io/RIKEN-SysSoft/ihk
 * branch            refs/changes/18/427618/6 -> FETCH_HEAD
HEAD is now at 06c6ab6 build system: switch to cmake
MCKBUILD=/work/mcktest/work_development@{1550042017}_refs-changes-18-427618-6/build
MCKINSTALL=/work/mcktest/work_development@{1550042017}_refs-changes-18-427618-6/mck
/work/mcktest/bin/config_and_build_smp_x86.sh: line 36: /work/mcktest/work_development@{1550042017}_refs-changes-18-427618-6/src/ihk/configure: No such file or directory
ERROR: autobuild.sh failed

Patch-set: 6