Update patch set 1
Patch Set 1: Build-arm64-1

apollo15: build report: build failed:
[  7%] Generating kmod_always_rebuild
[ 14%] Building kmod ihk
[ 21%] Built target ihk_ko
[ 35%] Built target ihklib
[ 50%] Built target ihkosctl
[ 64%] Built target ihkconfig
[ 78%] Built target ihkmond
[ 85%] Generating old_timestamp, arch/arm64/smp-arm64-startup.o, arch/arm64/smp-arm64-trampoline.o, arch/arm64/smp-arch-driver.o, smp-driver.o, arch/arm64/.smp-arm64-startup.o.cmd, arch/arm64/.smp-arm64-trampoline.o.cmd, arch/arm64/.smp-arch-driver.o.cmd, .smp-driver.o.cmd, ihk-smp-arm64.o, .ihk-smp-arm64.o.cmd, ihk-smp-arm64.mod.c, ihk-smp-arm64.mod.o, .ihk-smp-arm64.mod.o.cmd, .ihk-smp-arm64.ko.cmd, .tmp_versions/ihk-smp-arm64.mod, .tmp_versions, modules.order
[ 92%] Building kmod ihk-smp-arm64
/tmp/ihk/linux/driver/smp/smp-driver.c: In function ‘smp_ihk_os_panic_notifier’:
/tmp/ihk/linux/driver/smp/smp-driver.c:2831:2: error: ‘status’ undeclared (first use in this function)
  status = smp_ihk_os_query_status(ihk_os, priv);
  ^
/tmp/ihk/linux/driver/smp/smp-driver.c:2831:2: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [/tmp/build-ihk/linux/driver/smp/smp-driver.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-ihk/linux/driver/smp] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [linux/driver/smp/ihk-smp-arm64.ko] Error 2
make[2]: Target `linux/driver/smp/CMakeFiles/ihk-smp-arm64_ko.dir/build' not remade because of errors.
make[1]: *** [linux/driver/smp/CMakeFiles/ihk-smp-arm64_ko.dir/all] Error 2
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1