Update patch set 2
Patch Set 2: Verified-1

ihk build failed:
make[1]: Entering directory `/tmp/build/ihk/linux/core'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/ihk/linux/core SUBDIRS=/tmp/build/ihk/linux/core ARCH=x86_64 modules
make[2]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  CC [M]  /tmp/build/ihk/linux/core/../../ikc/queue.o
/work/mcktest/git/ihk/../ihk/linux/core/../../ikc/queue.c: In function ‘ihk_ikc_recv_handler’:
/work/mcktest/git/ihk/../ihk/linux/core/../../ikc/queue.c:545:12: error: too many arguments to function ‘ihk_ikc_release_packet’
            channel);
            ^
/work/mcktest/git/ihk/../ihk/linux/core/../../ikc/queue.c:289:6: note: declared here
 void ihk_ikc_release_packet(struct ihk_ikc_free_packet *p)
      ^
make[3]: *** [/tmp/build/ihk/linux/core/../../ikc/queue.o] Error 1
make[3]: Target `__build' not remade because of errors.
make[2]: *** [_module_/tmp/build/ihk/linux/core] Error 2
make[2]: Target `modules' not remade because of errors.
make[2]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[1]: *** [modules] Error 2
make[1]: Leaving directory `/tmp/build/ihk/linux/core'
make: *** [core-modules] Error 2
make[1]: Entering directory `/tmp/build/ihk/linux/user'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/tmp/build/ihk/linux/user'
make: Target `all' not remade because of errors.

Patch-set: 2
Reviewer: riken-syssoft-gerrit <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1