Update patch set 2
Patch Set 2: Verified-1

wallaby7: build failed:
[ 10%] Generating kmod_always_rebuild
[ 20%] Building kmod ihk
[ 30%] Built target ihk_ko
[ 40%] Built target ihklib
[ 50%] Built target ihkconfig
[ 60%] Built target ihkmond
[ 70%] Built target ihkosctl
[ 80%] Generating old_timestamp, arch/x86_64/smp-x86_64-startup.o, arch/x86_64/smp-x86_64-trampoline.o, arch/x86_64/smp-arch-driver.o, smp-driver.o, arch/x86_64/.smp-x86_64-startup.o.cmd, arch/x86_64/.smp-x86_64-trampoline.o.cmd, arch/x86_64/.smp-arch-driver.o.cmd, .smp-driver.o.cmd, ihk-smp-x86_64.o, .ihk-smp-x86_64.o.cmd, ihk-smp-x86_64.mod.c, ihk-smp-x86_64.mod.o, .ihk-smp-x86_64.mod.o.cmd, .ihk-smp-x86_64.ko.cmd, .tmp_versions/ihk-smp-x86_64.mod, .tmp_versions, modules.order
[ 90%] Building kmod ihk-smp-x86_64
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c: In function ‘smp_ihk_os_boot’:
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:606:24: error: ‘struct ihk_smp_boot_param_memory_chunk’ has no member named ‘tofu_dma_addr’
     memset(bp_mem_chunk->tofu_dma_addr,
                        ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:607:29: error: ‘struct ihk_smp_boot_param_memory_chunk’ has no member named ‘tofu_dma_addr’
       0, sizeof(bp_mem_chunk->tofu_dma_addr));
                             ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:612:19: error: ‘struct ihk_smp_boot_param_memory_chunk’ has no member named ‘tofu_dma_addr’
       bp_mem_chunk->tofu_dma_addr[tni][cq] =
                   ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:629:53: error: ‘struct ihk_smp_boot_param_memory_chunk’ has no member named ‘tofu_dma_addr’
     memcpy(os_mem_chunk->tofu_dma_addr, bp_mem_chunk->tofu_dma_addr,
                                                     ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:630:25: error: ‘struct ihk_smp_boot_param_memory_chunk’ has no member named ‘tofu_dma_addr’
      sizeof(bp_mem_chunk->tofu_dma_addr));
                         ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c: In function ‘__ihk_smp_reserve_mem’:
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:3390:6: error: ‘__GFP_ATOMIC’ undeclared (first use in this function)
      __GFP_ATOMIC | __GFP_HIGH | __GFP_THISNODE | __GFP_NOFAIL,
      ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:3390:6: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [/tmp/build-ihk/linux/driver/smp/smp-driver.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-ihk/linux/driver/smp] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [linux/driver/smp/ihk-smp-x86_64.ko] Error 2
make[2]: Target `linux/driver/smp/CMakeFiles/ihk-smp-x86_64_ko.dir/build' not remade because of errors.
make[1]: *** [linux/driver/smp/CMakeFiles/ihk-smp-x86_64_ko.dir/all] Error 2
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1