Update patch set 4
Patch Set 4: Build-arm64-1

apollo15: build report: build failed:
[ 10%] Generating kmod_always_rebuild
[ 20%] Building kmod ihk
[ 30%] Built target ihk_ko
[ 40%] Built target ihklib
[ 50%] Built target ihkconfig
[ 60%] Built target ihkmond
[ 70%] Built target ihkosctl
[ 80%] Generating old_timestamp, arch/arm64/smp-arm64-startup.o, arch/arm64/smp-arm64-trampoline.o, arch/arm64/smp-arch-driver.o, smp-driver.o, arch/arm64/.smp-arm64-startup.o.cmd, arch/arm64/.smp-arm64-trampoline.o.cmd, arch/arm64/.smp-arch-driver.o.cmd, .smp-driver.o.cmd, ihk-smp-arm64.o, .ihk-smp-arm64.o.cmd, ihk-smp-arm64.mod.c, ihk-smp-arm64.mod.o, .ihk-smp-arm64.mod.o.cmd, .ihk-smp-arm64.ko.cmd, .tmp_versions/ihk-smp-arm64.mod, .tmp_versions, modules.order
[ 90%] Building kmod ihk-smp-arm64
/tmp/ihk/linux/driver/smp/arch/arm64/smp-arch-driver.c: In function ‘smp_ihk_setup_trampoline’:
/tmp/ihk/linux/driver/smp/arch/arm64/smp-arch-driver.c:1152:3: error: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘long long unsigned int’ [-Werror=format=]
   (uint64_t)ihk__init_mm->pgd, (uint64_t)virt_to_phys(ihk__init_mm->pgd));
   ^
/tmp/ihk/linux/driver/smp/arch/arm64/smp-arch-driver.c:1152:3: error: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘phys_addr_t’ [-Werror=format=]
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-ihk/linux/driver/smp/arch/arm64/smp-arch-driver.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-ihk/linux/driver/smp] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [linux/driver/smp/ihk-smp-arm64.ko] Error 2
make[2]: Target `linux/driver/smp/CMakeFiles/ihk-smp-arm64_ko.dir/build' not remade because of errors.
make[1]: *** [linux/driver/smp/CMakeFiles/ihk-smp-arm64_ko.dir/all] Error 2
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 4
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1