Update patch set 7
Patch Set 7:

MCKERNEL : mckernel-development@{1550042214}-?
IHK      : ihk-development@{1550042214}-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/ihk/+/427618/7 // c66026d1e1818923f19953ff42d6f30307d0f997
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_development@{1550042214}_refs-changes-18-427618-7
START : 20190213191514
END   : 20190213191517

HEAD is now at 34a995d perfctr_stop: add flags to no 'disable_intens'
From https://review.gerrithub.io/RIKEN-SysSoft/ihk
 * branch            refs/changes/18/427618/7 -> FETCH_HEAD
HEAD is now at c66026d build system: switch to cmake
MCKBUILD=/work/mcktest/work_development@{1550042214}_refs-changes-18-427618-7/build
MCKINSTALL=/work/mcktest/work_development@{1550042214}_refs-changes-18-427618-7/mck
/work/mcktest/bin/config_and_build_smp_x86.sh: line 36: /work/mcktest/work_development@{1550042214}_refs-changes-18-427618-7/src/ihk/configure: No such file or directory
ERROR: autobuild.sh failed

Patch-set: 7
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>