Update patch set 1
Patch Set 1: Verified-1

build failed:
[ 10%] Generating kmod_always_rebuild
[ 20%] Building kmod ihk
[ 30%] Built target ihk_ko
[ 40%] Built target ihklib
[ 50%] Built target ihkconfig
[ 60%] Built target ihkmond
[ 70%] Built target ihkosctl
[ 80%] Generating old_timestamp, arch/x86_64/smp-x86_64-startup.o, arch/x86_64/smp-x86_64-trampoline.o, arch/x86_64/smp-arch-driver.o, smp-driver.o, arch/x86_64/.smp-x86_64-startup.o.cmd, arch/x86_64/.smp-x86_64-trampoline.o.cmd, arch/x86_64/.smp-arch-driver.o.cmd, .smp-driver.o.cmd, ihk-smp-x86_64.o, .ihk-smp-x86_64.o.cmd, ihk-smp-x86_64.mod.c, ihk-smp-x86_64.mod.o, .ihk-smp-x86_64.mod.o.cmd, .ihk-smp-x86_64.ko.cmd, .tmp_versions/ihk-smp-x86_64.mod, .tmp_versions, modules.order
[ 90%] Building kmod ihk-smp-x86_64
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:372:20: error: redefinition of ‘rdtsc’
 unsigned long long rdtsc(void)
                    ^
In file included from ./arch/x86/include/asm/processor.h:20:0,
                 from ./arch/x86/include/asm/thread_info.h:22,
                 from include/linux/thread_info.h:54,
                 from ./arch/x86/include/asm/elf.h:7,
                 from include/linux/elf.h:4,
                 from /work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:14:
./arch/x86/include/asm/msr.h:121:43: note: previous definition of ‘rdtsc’ was here
 static __always_inline unsigned long long rdtsc(void)
                                           ^
make[4]: *** [/tmp/build-ihk/linux/driver/smp/smp-driver.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-ihk/linux/driver/smp] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [linux/driver/smp/ihk-smp-x86_64.ko] Error 2
make[2]: Target `linux/driver/smp/CMakeFiles/ihk-smp-x86_64_ko.dir/build' not remade because of errors.
make[1]: *** [linux/driver/smp/CMakeFiles/ihk-smp-x86_64_ko.dir/all] Error 2
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1