Update patch set 1
Patch Set 1: Build-arm64-1

apollo15: build report: build failed:
[ 10%] Generating kmod_always_rebuild
[ 20%] Building kmod ihk
[ 30%] Built target ihk_ko
[ 40%] Built target ihklib
[ 50%] Building C object linux/user/CMakeFiles/ihkconfig.dir/ihkconfig.c.o
/tmp/ihk/linux/user/ihkconfig.c: In function ‘do_reserve’:
/tmp/ihk/linux/user/ihkconfig.c:242:3: error: implicit declaration of function ‘ihk_reserve_cpu_str’ [-Werror=implicit-function-declaration]
   ret = ihk_reserve_cpu_str(index, __argv[4], NULL);
   ^
/tmp/ihk/linux/user/ihkconfig.c:250:3: error: implicit declaration of function ‘ihk_reserve_mem_str’ [-Werror=implicit-function-declaration]
   ret = ihk_reserve_mem_str(index, __argv[4], NULL);
   ^
/tmp/ihk/linux/user/ihkconfig.c:232:11: error: unused variable ‘count’ [-Werror=unused-variable]
  int ret, count;
           ^
cc1: all warnings being treated as errors
make[2]: *** [linux/user/CMakeFiles/ihkconfig.dir/ihkconfig.c.o] Error 1
make[2]: Target `linux/user/CMakeFiles/ihkconfig.dir/build' not remade because of errors.
make[1]: *** [linux/user/CMakeFiles/ihkconfig.dir/all] Error 2
[ 60%] Built target ihkmond
[ 70%] Built target ihkosctl
[ 80%] Generating kmod_always_rebuild
[ 90%] Building kmod ihk-smp-arm64
[100%] Built target ihk-smp-arm64_ko
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1