Update patch set 1
Patch Set 1: Verified-1

wallaby7: build failed:
[  7%] Generating old_timestamp, host_driver.o, mem_alloc.o, mm.o, mikc.o, ../../ikc/linux.o, ../../ikc/master.o, ../../ikc/queue.o, .host_driver.o.cmd, .mem_alloc.o.cmd, .mm.o.cmd, .mikc.o.cmd, ../../ikc/.linux.o.cmd, ../../ikc/.master.o.cmd, ../../ikc/.queue.o.cmd, ihk.o, .ihk.o.cmd, ihk.mod.c, ihk.mod.o, .ihk.mod.o.cmd, .ihk.ko.cmd, .tmp_versions/ihk.mod, .tmp_versions, modules.order
[ 14%] Building kmod ihk
/work/mcktest/git/ihk/linux/core/host_driver.c: In function ‘ihk_host_device_ioctl’:
/work/mcktest/git/ihk/linux/core/host_driver.c:2020:7: error: ‘IHK_DEVICE_DETECT_HUNGUP’ undeclared (first use in this function)
  case IHK_DEVICE_DETECT_HUNGUP:
       ^
/work/mcktest/git/ihk/linux/core/host_driver.c:2020:7: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [/tmp/build-ihk/linux/core/host_driver.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-ihk/linux/core] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [linux/core/ihk.ko] Error 2
make[2]: Target `linux/core/CMakeFiles/ihk_ko.dir/build' not remade because of errors.
make[1]: *** [linux/core/CMakeFiles/ihk_ko.dir/all] Error 2
[ 28%] Built target ihklib
[ 42%] Built target ihkosctl
[ 57%] Built target ihkconfig
[ 64%] Building C object linux/user/CMakeFiles/ihkmond.dir/ihkmond.c.o
/work/mcktest/git/ihk/linux/user/ihkmond.c: In function ‘detect_hungup’:
/work/mcktest/git/ihk/linux/user/ihkmond.c:164:25: error: ‘IHK_DEVICE_DETECT_HUNGUP’ undeclared (first use in this function)
  ret_lib = ioctl(devfd, IHK_DEVICE_DETECT_HUNGUP,
                         ^
/work/mcktest/git/ihk/linux/user/ihkmond.c:164:25: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [linux/user/CMakeFiles/ihkmond.dir/ihkmond.c.o] Error 1
make[2]: Target `linux/user/CMakeFiles/ihkmond.dir/build' not remade because of errors.
make[1]: *** [linux/user/CMakeFiles/ihkmond.dir/all] Error 2
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1