Update patch set 2
Patch Set 2:

MCKERNEL : mckernel-development-?
IHK      : ihk-development-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/ihk/+/427618/2 // 29be5441f0d79170ca63e1abfd04a48e8d71572c
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_development_refs-changes-18-427618-2
START : 20181013211221
END   : 20181013211230

--2018-10-13 21:12:21--  https://postpeta.pccluster.org/gitweb/?p=mckernel.git;a=snapshot;h=development;sf=tgz
Resolving wallaby (wallaby)... 10.0.1.1
Connecting to wallaby (wallaby)|10.0.1.1|:80... connected.
Proxy request sent, awaiting response... 401 Authorization Required
Connecting to wallaby (wallaby)|10.0.1.1|:80... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/work/mcktest/work_development_refs-changes-18-427618-2/src/mckernel.tgz’

     0K .......... .......... .......... .......... .......... 1.62M
    50K .......... .......... .......... .......... .......... 2.86M
   100K .......... .......... .......... .......... .......... 4.23M
   150K .......... .......... .......... .......... .......... 4.30M
   200K .......... .......... .......... .......... .......... 8.12M
   250K .......... .......... .......... .......... .......... 6.19M
   300K .......... .......... .......... .......... .......... 5.35M
   350K .......... .......... .......... .......... .......... 8.51M
   400K .......... .......... .......... .......... .......... 6.46M
   450K .......... .......... .......... .......... .......... 13.0M
   500K .......... .......... .......... .......... .......... 6.38M
   550K .......... .......... .......... .......... .......... 5.91M
   600K .......... .......... .......... .......... .......... 15.7M
   650K .......... .......... .......... .......... .......... 6.12M
   700K .......... .......... .......... .......... .......... 15.2M
   750K .......... .......... .......... .......... .......... 6.19M
   800K .......... .......... .......... .......... .......... 14.9M
   850K .......... .......... .......... .......... .......... 8.29M
   900K .......... .......... .......... .......... .......... 9.44M
   950K .......... .......... .......... .......... .......... 25.7M
  1000K .......... .......... .......... .......... .......... 5.50M
  1050K .......... .......... .......... .......... .......... 37.9M
  1100K .......... .......... .......... .......... .......... 5.83M
  1150K .......... .                                            207M=0.2s

2018-10-13 21:12:23 (6.19 MB/s) - ‘/work/mcktest/work_development_refs-changes-18-427618-2/src/mckernel.tgz’ saved [1189571]

From ssh://review.gerrithub.io/RIKEN-SysSoft/ihk
 * branch            refs/changes/18/427618/2 -> FETCH_HEAD
HEAD is now at 29be544 build system: switch to cmake
MCKBUILD=/work/mcktest/work_development_refs-changes-18-427618-2/build
MCKINSTALL=/work/mcktest/work_development_refs-changes-18-427618-2/mck
/work/mcktest/bin/config_and_build_smp_x86.sh: line 24: /work/mcktest/work_development_refs-changes-18-427618-2/src/ihk/configure: No such file or directory
ERROR: autobuild.sh failed

Patch-set: 2
Reviewer: syssoft-gerrit@ml.riken.jp <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>