Update patch set 6
Patch Set 6: Verified-1

build failed:
[ 10%] Generating kmod_always_rebuild
[ 20%] Building kmod ihk
[ 30%] Built target ihk_ko
[ 40%] Building C object linux/user/CMakeFiles/ihklib.dir/ihklib.c.o
/work/mcktest/git/ihk/linux/user/ihklib.c:1683:5: error: redefinition of ‘ihklib_os_open’
 int ihklib_os_open(int index)
     ^
/work/mcktest/git/ihk/linux/user/ihklib.c:1655:5: note: previous definition of ‘ihklib_os_open’ was here
 int ihklib_os_open(int index)
     ^
make[2]: *** [linux/user/CMakeFiles/ihklib.dir/ihklib.c.o] Error 1
make[2]: Target `linux/user/CMakeFiles/ihklib.dir/build' not remade because of errors.
make[1]: *** [linux/user/CMakeFiles/ihklib.dir/all] Error 2
[ 50%] Generating kmod_always_rebuild
[ 60%] Building kmod ihk-smp-x86_64
[ 70%] Built target ihk-smp-x86_64_ko
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 6
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1