Update patch set 3
Patch Set 3: Build-arm64-1

apollo15: build report: build failed:
[ 10%] Generating kmod_always_rebuild
[ 20%] Building kmod ihk
[ 30%] Built target ihk_ko
[ 40%] Building C object linux/user/CMakeFiles/ihklib.dir/ihklib.c.o
/tmp/ihk/linux/user/ihklib.c: In function ‘ihk_reserve_mem’:
/tmp/ihk/linux/user/ihklib.c:1258:18: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
     if (req.sizes[i] < 0) {
                  ^
cc1: all warnings being treated as errors
make[2]: *** [linux/user/CMakeFiles/ihklib.dir/ihklib.c.o] Error 1
make[2]: Target `linux/user/CMakeFiles/ihklib.dir/build' not remade because of errors.
make[1]: *** [linux/user/CMakeFiles/ihklib.dir/all] Error 2
[ 50%] Generating kmod_always_rebuild
[ 60%] Building kmod ihk-smp-arm64
[ 70%] Built target ihk-smp-arm64_ko
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 3
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1