Update patch set 1
Patch Set 1: Verified-1

wallaby7: build failed:
[ 10%] Generating kmod_always_rebuild
[ 20%] Building kmod ihk
[ 30%] Built target ihk_ko
[ 40%] Building C object linux/user/CMakeFiles/ihklib.dir/ihklib.c.o
/work/mcktest/git/ihk/linux/user/ihklib.c: In function ‘cpu_str2req’:
/work/mcktest/git/ihk/linux/user/ihklib.c:50:2: error: ‘fd’ undeclared (first use in this function)
  fd = open("/dev/kmsg", O_WRONLY);    \
  ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:236:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: invalid req pointer (NULL)\n", __func__);
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:50:2: note: each undeclared identifier is reported only once for each function it appears in
  fd = open("/dev/kmsg", O_WRONLY);    \
  ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:236:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: invalid req pointer (NULL)\n", __func__);
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:43:6: error: unused variable ‘_fd’ [-Werror=unused-variable]
  int _fd;       \
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:236:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: invalid req pointer (NULL)\n", __func__);
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c: In function ‘ikc_str2req’:
/work/mcktest/git/ihk/linux/user/ihklib.c:50:2: error: ‘fd’ undeclared (first use in this function)
  fd = open("/dev/kmsg", O_WRONLY);    \
  ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:531:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: invalid req pointer (NULL)\n", __func__);
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:43:6: error: unused variable ‘_fd’ [-Werror=unused-variable]
  int _fd;       \
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:531:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: invalid req pointer (NULL)\n", __func__);
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c: In function ‘ikc_req2str’:
/work/mcktest/git/ihk/linux/user/ihklib.c:50:2: error: ‘fd’ undeclared (first use in this function)
  fd = open("/dev/kmsg", O_WRONLY);    \
  ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:671:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: allocating rank\n", __func__);
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:43:6: error: unused variable ‘_fd’ [-Werror=unused-variable]
  int _fd;       \
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:671:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: allocating rank\n", __func__);
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:43:6: error: unused variable ‘_fd’ [-Werror=unused-variable]
  int _fd;       \
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:677:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: allocating num_ikc_ssets\n", __func__);
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:43:6: error: unused variable ‘_fd’ [-Werror=unused-variable]
  int _fd;       \
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:683:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: allocating ikc_sset_members\n", __func__);
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:43:6: error: unused variable ‘_fd’ [-Werror=unused-variable]
  int _fd;       \
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:706:5: note: in expansion of macro ‘eprintf’
     eprintf("%s: error: allocating ikc_sset_members\n",
     ^
/work/mcktest/git/ihk/linux/user/ihklib.c: In function ‘ihk_get_num_reserved_mem_chunks’:
/work/mcktest/git/ihk/linux/user/ihklib.c:43:6: error: unused variable ‘_fd’ [-Werror=unused-variable]
  int _fd;       \
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:1414:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: ihklib_device_open\n",
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c: In function ‘ihk_os_release_mem’:
/work/mcktest/git/ihk/linux/user/ihklib.c:43:6: error: unused variable ‘_fd’ [-Werror=unused-variable]
  int _fd;       \
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2488:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: allocating request numa_ids\n",
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:43:6: error: unused variable ‘_fd’ [-Werror=unused-variable]
  int _fd;       \
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2501:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: ihklib_os_open\n",
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c: In function ‘ihk_os_shutdown’:
/work/mcktest/git/ihk/linux/user/ihklib.c:43:6: error: unused variable ‘_fd’ [-Werror=unused-variable]
  int _fd;       \
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2709:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: ihklib_os_open\n",
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c: In function ‘ihklib_os_query_mem_sysfs’:
/work/mcktest/git/ihk/linux/user/ihklib.c:50:2: error: ‘fd’ undeclared (first use in this function)
  fd = open("/dev/kmsg", O_WRONLY);    \
  ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2967:5: note: in expansion of macro ‘eprintf’
     eprintf("%s: error: type string (%s) is too long\n",
     ^
/work/mcktest/git/ihk/linux/user/ihklib.c:43:6: error: unused variable ‘_fd’ [-Werror=unused-variable]
  int _fd;       \
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2967:5: note: in expansion of macro ‘eprintf’
     eprintf("%s: error: type string (%s) is too long\n",
     ^
/work/mcktest/git/ihk/linux/user/ihklib.c: In function ‘ihklib_os_query_mem’:
/work/mcktest/git/ihk/linux/user/ihklib.c:43:6: error: unused variable ‘_fd’ [-Werror=unused-variable]
  int _fd;       \
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:3022:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: ihklib_os_open\n",
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:43:6: error: unused variable ‘_fd’ [-Werror=unused-variable]
  int _fd;       \
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:3037:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: error: actual # of NUMA nodes (%d) != requested (%d)\n",
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c: In function ‘ihk_os_set_ikc_map_str’:
/work/mcktest/git/ihk/linux/user/ihklib.c:50:2: error: ‘fd’ undeclared (first use in this function)
  fd = open("/dev/kmsg", O_WRONLY);    \
  ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:4032:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: ikc_str2array failed with %d\n",
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:43:6: error: unused variable ‘_fd’ [-Werror=unused-variable]
  int _fd;       \
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c:72:3: note: in expansion of macro ‘printk’
   printk(fmt, ##args);  \
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:4032:3: note: in expansion of macro ‘eprintf’
   eprintf("%s: ikc_str2array failed with %d\n",
   ^
cc1: all warnings being treated as errors
make[2]: *** [linux/user/CMakeFiles/ihklib.dir/ihklib.c.o] Error 1
make[2]: Target `linux/user/CMakeFiles/ihklib.dir/build' not remade because of errors.
make[1]: *** [linux/user/CMakeFiles/ihklib.dir/all] Error 2
[ 50%] Generating kmod_always_rebuild
[ 60%] Building kmod ihk-smp-x86_64
[ 70%] Built target ihk-smp-x86_64_ko
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1