Update patch set 2
Patch Set 2: Verified-1

wallaby7: build failed:
[  7%] Generating kmod_always_rebuild
[ 14%] Building kmod ihk
[ 21%] Built target ihk_ko
[ 35%] Built target ihklib
[ 50%] Built target ihkosctl
[ 64%] Built target ihkconfig
[ 78%] Built target ihkmond
[ 85%] Generating old_timestamp, arch/x86_64/smp-x86_64-startup.o, arch/x86_64/smp-x86_64-trampoline.o, arch/x86_64/smp-arch-driver.o, smp-driver.o, arch/x86_64/.smp-x86_64-startup.o.cmd, arch/x86_64/.smp-x86_64-trampoline.o.cmd, arch/x86_64/.smp-arch-driver.o.cmd, .smp-driver.o.cmd, ihk-smp-x86_64.o, .ihk-smp-x86_64.o.cmd, ihk-smp-x86_64.mod.c, ihk-smp-x86_64.mod.o, .ihk-smp-x86_64.mod.o.cmd, .ihk-smp-x86_64.ko.cmd, .tmp_versions/ihk-smp-x86_64.mod, .tmp_versions, modules.order
[ 92%] Building kmod ihk-smp-x86_64
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c: In function ‘smp_ihk_os_shutdown’:
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:1244:7: error: ‘BUILTIN_OS_STATUS_LOADED’ undeclared (first use in this function)
  case BUILTIN_OS_STATUS_LOADED:
       ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:1244:7: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [/tmp/build-ihk/linux/driver/smp/smp-driver.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-ihk/linux/driver/smp] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [linux/driver/smp/ihk-smp-x86_64.ko] Error 2
make[2]: Target `linux/driver/smp/CMakeFiles/ihk-smp-x86_64_ko.dir/build' not remade because of errors.
make[1]: *** [linux/driver/smp/CMakeFiles/ihk-smp-x86_64_ko.dir/all] Error 2
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1