Update patch set 3
Patch Set 3: Verified-1

build failed:
[ 10%] Generating kmod_always_rebuild
[ 20%] Building kmod ihk
[ 30%] Built target ihk_ko
[ 40%] Building C object linux/user/CMakeFiles/ihklib.dir/ihklib.c.o
/work/mcktest/git/ihk/linux/user/ihklib.c: In function ‘ihk_reserve_mem’:
/work/mcktest/git/ihk/linux/user/ihklib.c:1152:18: error: unused variable ‘ave_min’ [-Werror=unused-variable]
    unsigned long ave_min = ave_requested - min;
                  ^
/work/mcktest/git/ihk/linux/user/ihklib.c:1151:18: error: unused variable ‘max_ave’ [-Werror=unused-variable]
    unsigned long max_ave = max - ave_requested;
                  ^
/work/mcktest/git/ihk/linux/user/ihklib.c: In function ‘ihk_os_setperfevent’:
/work/mcktest/git/ihk/linux/user/ihklib.c:2971:2: error: ‘ret_ioctl’ undeclared (first use in this function)
  ret_ioctl = ioctl(fd, IHK_OS_AUX_PERF_NUM, n);
  ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2971:2: note: each undeclared identifier is reported only once for each function it appears in
/work/mcktest/git/ihk/linux/user/ihklib.c:2976:10: error: ‘errno_save’ undeclared (first use in this function)
   ret = -errno_save;
          ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2977:3: error: label ‘out’ used but not defined
   goto out;
   ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2959:6: error: variable ‘ret’ set but not used [-Werror=unused-but-set-variable]
  int ret;
      ^
/work/mcktest/git/ihk/linux/user/ihklib.c: At top level:
/work/mcktest/git/ihk/linux/user/ihklib.c:2980:2: error: data definition has no type or storage class [-Werror]
  ret = ioctl(fd, IHK_OS_AUX_PERF_SET, attr);
  ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2980:2: error: type defaults to ‘int’ in declaration of ‘ret’ [-Werror=implicit-int]
/work/mcktest/git/ihk/linux/user/ihklib.c:2980:14: error: ‘fd’ undeclared here (not in a function)
  ret = ioctl(fd, IHK_OS_AUX_PERF_SET, attr);
              ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2980:39: error: ‘attr’ undeclared here (not in a function)
  ret = ioctl(fd, IHK_OS_AUX_PERF_SET, attr);
                                       ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2981:2: error: expected identifier or ‘(’ before ‘if’
  if (ret < 0) {
  ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2990:5: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘:’ token
  out:
     ^
/work/mcktest/git/ihk/linux/user/ihklib.c:65:31: error: expected identifier or ‘(’ before ‘do’
 #define dprintk(fmt, args...) do {  } while (0)
                               ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2994:2: note: in expansion of macro ‘dprintk’
  dprintk("%s: returning %d\n", __func__, ret);
  ^
/work/mcktest/git/ihk/linux/user/ihklib.c:65:39: error: expected identifier or ‘(’ before ‘while’
 #define dprintk(fmt, args...) do {  } while (0)
                                       ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2994:2: note: in expansion of macro ‘dprintk’
  dprintk("%s: returning %d\n", __func__, ret);
  ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2995:2: error: expected identifier or ‘(’ before ‘return’
  return ret;
  ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2996:1: error: expected identifier or ‘(’ before ‘}’ token
 }
 ^
cc1: all warnings being treated as errors
make[2]: *** [linux/user/CMakeFiles/ihklib.dir/ihklib.c.o] Error 1
make[2]: Target `linux/user/CMakeFiles/ihklib.dir/build' not remade because of errors.
make[1]: *** [linux/user/CMakeFiles/ihklib.dir/all] Error 2
[ 50%] Generating kmod_always_rebuild
[ 60%] Building kmod ihk-smp-x86_64
[ 70%] Built target ihk-smp-x86_64_ko
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 3
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1