Update patch set 2
Patch Set 2: Verified-1

build failed:
[ 10%] Generating kmod_always_rebuild
[ 20%] Building kmod ihk
[ 30%] Built target ihk_ko
[ 40%] Building C object linux/user/CMakeFiles/ihklib.dir/ihklib.c.o
/work/mcktest/git/ihk/linux/user/ihklib.c: In function ‘ihk_reserve_mem’:
/work/mcktest/git/ihk/linux/user/ihklib.c:1192:5: error: ‘max_ave’ undeclared (first use in this function)
     max_ave, max_ave >> 20,
     ^
/work/mcktest/git/ihk/linux/user/ihklib.c:1192:5: note: each undeclared identifier is reported only once for each function it appears in
/work/mcktest/git/ihk/linux/user/ihklib.c:1193:5: error: ‘ave_min’ undeclared (first use in this function)
     ave_min, ave_min >> 20,
     ^
/work/mcktest/git/ihk/linux/user/ihklib.c:1195:2: error: #endif without #if
 #endif
  ^
make[2]: *** [linux/user/CMakeFiles/ihklib.dir/ihklib.c.o] Error 1
make[2]: Target `linux/user/CMakeFiles/ihklib.dir/build' not remade because of errors.
make[1]: *** [linux/user/CMakeFiles/ihklib.dir/all] Error 2
[ 50%] Generating kmod_always_rebuild
[ 60%] Building kmod ihk-smp-x86_64
[ 70%] Built target ihk-smp-x86_64_ko
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1