Update patch set 16
Patch Set 16: Verified-1

build failed:
[ 10%] Generating old_timestamp, host_driver.o, mem_alloc.o, mm.o, mikc.o, ../../ikc/linux.o, ../../ikc/master.o, ../../ikc/queue.o, .host_driver.o.cmd, .mem_alloc.o.cmd, .mm.o.cmd, .mikc.o.cmd, ../../ikc/.linux.o.cmd, ../../ikc/.master.o.cmd, ../../ikc/.queue.o.cmd, ihk.o, .ihk.o.cmd, ihk.mod.c, ihk.mod.o, .ihk.mod.o.cmd, .ihk.ko.cmd, .tmp_versions/ihk.mod, .tmp_versions, modules.order
[ 20%] Building kmod ihk
/work/mcktest/git/ihk/linux/core/host_driver.c: In function ‘__ihk_os_status’:
/work/mcktest/git/ihk/linux/core/host_driver.c:741:9: error: ‘status’ undeclared (first use in this function)
  return status;
         ^
/work/mcktest/git/ihk/linux/core/host_driver.c:741:9: note: each undeclared identifier is reported only once for each function it appears in
/work/mcktest/git/ihk/linux/core/host_driver.c:742:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-ihk/linux/core/host_driver.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-ihk/linux/core] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [linux/core/ihk.ko] Error 2
make[2]: Target `linux/core/CMakeFiles/ihk_ko.dir/build' not remade because of errors.
make[1]: *** [linux/core/CMakeFiles/ihk_ko.dir/all] Error 2
[ 30%] Built target ihklib
[ 40%] Built target ihkconfig
[ 50%] Built target ihkmond
[ 60%] Built target ihkosctl
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 16
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1