Update patch set 2
Patch Set 2: Verified-1

setns_dummy_uts: build failed:
[ 10%] Generating kmod_always_rebuild
[ 20%] Building kmod ihk
[ 30%] Built target ihk_ko
[ 40%] Built target ihklib
[ 50%] Built target ihkconfig
[ 60%] Built target ihkmond
[ 70%] Built target ihkosctl
[ 80%] Generating old_timestamp, arch/x86_64/smp-x86_64-startup.o, arch/x86_64/smp-x86_64-trampoline.o, arch/x86_64/smp-arch-driver.o, smp-driver.o, arch/x86_64/.smp-x86_64-startup.o.cmd, arch/x86_64/.smp-x86_64-trampoline.o.cmd, arch/x86_64/.smp-arch-driver.o.cmd, .smp-driver.o.cmd, ihk-smp-x86_64.o, .ihk-smp-x86_64.o.cmd, ihk-smp-x86_64.mod.c, ihk-smp-x86_64.mod.o, .ihk-smp-x86_64.mod.o.cmd, .ihk-smp-x86_64.ko.cmd, .tmp_versions/ihk-smp-x86_64.mod, .tmp_versions, modules.order
[ 90%] Building kmod ihk-smp-x86_64
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c: In function ‘__ihk_smp_reserve_mem’:
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:3337:6: error: ‘__GFP_ATOMIC’ undeclared (first use in this function)
      __GFP_ATOMIC | __GFP_HIGH | __GFP_THISNODE |
      ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:3337:6: note: each undeclared identifier is reported only once for each function it appears in
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c: In function ‘smp_ihk_query_mem’:
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4535:13: error: invalid storage class for function ‘free_info’
 static void free_info(void)
             ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4535:1: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
 static void free_info(void)
 ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4794:33: error: invalid storage class for function ‘smp_ihk_get_cpu_topology’
 static struct ihk_cpu_topology *smp_ihk_get_cpu_topology(ihk_device_t dev, void *priv, int hw_id)
                                 ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4810:34: error: invalid storage class for function ‘smp_ihk_get_node_topology’
 static struct ihk_node_topology *smp_ihk_get_node_topology(ihk_device_t dev, void *priv, int node)
                                  ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4831:12: error: invalid storage class for function ‘smp_ihk_linux_cpu_to_hw_id’
 static int smp_ihk_linux_cpu_to_hw_id(ihk_device_t dev, void *priv, int cpu)
            ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4860:12: error: invalid storage class for function ‘smp_ihk_init’
 static int smp_ihk_init(ihk_device_t ihk_dev, void *priv)
            ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4893:12: error: invalid storage class for function ‘smp_ihk_exit’
 static int smp_ihk_exit(ihk_device_t ihk_dev, void *priv)
            ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4925:2: error: initializer element is not constant
  .init = smp_ihk_init,
  ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4925:2: error: (near initialization for ‘smp_ihk_device_ops.init’)
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4926:2: error: initializer element is not constant
  .exit = smp_ihk_exit,
  ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4926:2: error: (near initialization for ‘smp_ihk_device_ops.exit’)
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4943:2: error: initializer element is not constant
  .get_cpu_topology = smp_ihk_get_cpu_topology,
  ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4943:2: error: (near initialization for ‘smp_ihk_device_ops.get_cpu_topology’)
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4944:2: error: initializer element is not constant
  .get_node_topology = smp_ihk_get_node_topology,
  ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4944:2: error: (near initialization for ‘smp_ihk_device_ops.get_node_topology’)
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4945:2: error: initializer element is not constant
  .linux_cpu_to_hw_id = smp_ihk_linux_cpu_to_hw_id,
  ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4945:2: error: (near initialization for ‘smp_ihk_device_ops.linux_cpu_to_hw_id’)
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4965:12: error: invalid storage class for function ‘ihk_smp_symbols_init’
 static int ihk_smp_symbols_init(void)
            ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:5016:19: error: invalid storage class for function ‘smp_module_init’
 static int __init smp_module_init(void)
                   ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:5043:20: error: invalid storage class for function ‘smp_module_exit’
 static void __exit smp_module_exit(void)
                    ^
In file included from /work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:13:0:
include/linux/init.h:298:27: error: invalid storage class for function ‘__inittest’
  static inline initcall_t __inittest(void)  \
                           ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:5049:1: note: in expansion of macro ‘module_init’
 module_init(smp_module_init);
 ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:5049:1: error: ‘alias’ attribute ignored [-Werror=attributes]
In file included from /work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:13:0:
include/linux/init.h:304:27: error: invalid storage class for function ‘__exittest’
  static inline exitcall_t __exittest(void)  \
                           ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:5050:1: note: in expansion of macro ‘module_exit’
 module_exit(smp_module_exit);
 ^
include/linux/init.h:304:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
  static inline exitcall_t __exittest(void)  \
  ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:5050:1: note: in expansion of macro ‘module_exit’
 module_exit(smp_module_exit);
 ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:5050:1: error: ‘alias’ attribute ignored [-Werror=attributes]
In file included from include/linux/module.h:17:0,
                 from /work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:14:
include/linux/moduleparam.h:21:1: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
 static const char __UNIQUE_ID(name)[]       \
 ^
include/linux/module.h:95:32: note: in expansion of macro ‘__MODULE_INFO’
 #define MODULE_INFO(tag, info) __MODULE_INFO(tag, tag, info)
                                ^
include/linux/module.h:133:34: note: in expansion of macro ‘MODULE_INFO’
 #define MODULE_LICENSE(_license) MODULE_INFO(license, _license)
                                  ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:5052:1: note: in expansion of macro ‘MODULE_LICENSE’
 MODULE_LICENSE("Dual BSD/GPL");
 ^
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:5052:1: error: expected declaration or statement at end of input
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c: At top level:
/work/mcktest/git/ihk/linux/driver/smp/smp-driver.c:4426:12: error: ‘smp_ihk_query_mem’ defined but not used [-Werror=unused-function]
 static int smp_ihk_query_mem(ihk_device_t ihk_dev, unsigned long arg)
            ^
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-ihk/linux/driver/smp/smp-driver.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-ihk/linux/driver/smp] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [linux/driver/smp/ihk-smp-x86_64.ko] Error 2
make[2]: Target `linux/driver/smp/CMakeFiles/ihk-smp-x86_64_ko.dir/build' not remade because of errors.
make[1]: *** [linux/driver/smp/CMakeFiles/ihk-smp-x86_64_ko.dir/all] Error 2
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1