Update patch set 5
Patch Set 5:

MCKERNEL : mckernel-development@{1550040862}-?
IHK      : ihk-development@{1550040862}-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/ihk/+/427618/5 // 86d54c463c5ea58a955a4b338227101c2336ab40
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_development@{1550040862}_refs-changes-18-427618-5
START : 20190213191459
END   : 20190213191504

From https://review.gerrithub.io/RIKEN-SysSoft/mckernel
   34a995d..66bc44f  development -> origin/development
Checking out files:  44% (880/1994)   Checking out files:  45% (898/1994)   Checking out files:  46% (918/1994)   Checking out files:  47% (938/1994)   Checking out files:  48% (958/1994)   Checking out files:  49% (978/1994)   Checking out files:  50% (997/1994)   Checking out files:  51% (1017/1994)   Checking out files:  52% (1037/1994)   Checking out files:  53% (1057/1994)   Checking out files:  54% (1077/1994)   Checking out files:  55% (1097/1994)   Checking out files:  56% (1117/1994)   Checking out files:  57% (1137/1994)   Checking out files:  58% (1157/1994)   Checking out files:  59% (1177/1994)   Checking out files:  60% (1197/1994)   Checking out files:  61% (1217/1994)   Checking out files:  62% (1237/1994)   Checking out files:  63% (1257/1994)   Checking out files:  64% (1277/1994)   Checking out files:  65% (1297/1994)   Checking out files:  66% (1317/1994)   Checking out files:  67% (1336/1994)   Checking out files:  68% (1356/1994)   Checking out files:  69% (1376/1994)   Checking out files:  70% (1396/1994)   Checking out files:  71% (1416/1994)   Checking out files:  72% (1436/1994)   Checking out files:  73% (1456/1994)   Checking out files:  74% (1476/1994)   Checking out files:  75% (1496/1994)   Checking out files:  76% (1516/1994)   Checking out files:  77% (1536/1994)   Checking out files:  78% (1556/1994)   Checking out files:  79% (1576/1994)   Checking out files:  80% (1596/1994)   Checking out files:  81% (1616/1994)   Checking out files:  82% (1636/1994)   Checking out files:  83% (1656/1994)   Checking out files:  84% (1675/1994)   Checking out files:  85% (1695/1994)   Checking out files:  86% (1715/1994)   Checking out files:  87% (1735/1994)   Checking out files:  88% (1755/1994)   Checking out files:  89% (1775/1994)   Checking out files:  90% (1795/1994)   Checking out files:  91% (1815/1994)   Checking out files:  92% (1835/1994)   Checking out files:  93% (1855/1994)   Checking out files:  94% (1875/1994)   Checking out files:  95% (1895/1994)   Checking out files:  96% (1915/1994)   Checking out files:  97% (1935/1994)   Checking out files:  98% (1955/1994)   Checking out files:  99% (1975/1994)   Checking out files: 100% (1994/1994)   Checking out files: 100% (1994/1994), done.
HEAD is now at 34a995d perfctr_stop: add flags to no 'disable_intens'
From https://review.gerrithub.io/RIKEN-SysSoft/ihk
 * branch            refs/changes/18/427618/5 -> FETCH_HEAD
HEAD is now at 86d54c4 build system: switch to cmake
MCKBUILD=/work/mcktest/work_development@{1550040862}_refs-changes-18-427618-5/build
MCKINSTALL=/work/mcktest/work_development@{1550040862}_refs-changes-18-427618-5/mck
/work/mcktest/bin/config_and_build_smp_x86.sh: line 36: /work/mcktest/work_development@{1550040862}_refs-changes-18-427618-5/src/ihk/configure: No such file or directory
ERROR: autobuild.sh failed

Patch-set: 5