Update patch set 4
Patch Set 4:

MCKERNEL : mckernel-development@{1549603537}-?
IHK      : ihk-development@{1549603537}-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/ihk/+/427618/4 // 24a10d936c0ab14c6d55f3871c002410447a6c81
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_development@{1549603537}_refs-changes-18-427618-4
START : 20190212072349
END   : 20190212072352

HEAD is now at f5023c9 page fault handler: protect thread accesses
From https://review.gerrithub.io/RIKEN-SysSoft/ihk
 * branch            refs/changes/18/427618/4 -> FETCH_HEAD
HEAD is now at 24a10d9 build system: switch to cmake
MCKBUILD=/work/mcktest/work_development@{1549603537}_refs-changes-18-427618-4/build
MCKINSTALL=/work/mcktest/work_development@{1549603537}_refs-changes-18-427618-4/mck
/work/mcktest/bin/config_and_build_smp_x86.sh: line 36: /work/mcktest/work_development@{1549603537}_refs-changes-18-427618-4/src/ihk/configure: No such file or directory
ERROR: autobuild.sh failed

Patch-set: 4
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>