Update patch set 1
Patch Set 1: Build-arm64-1

apollo15: build report: ihk build failed:
++ make -k
make[1]: Entering directory `/tmp/build/ihk/linux/core'
make -C /lib/modules/4.14.0-115.13.1.1chaos.el7a.aarch64/build M=/tmp/build/ihk/linux/core SUBDIRS=/tmp/build/ihk/linux/core ARCH=aarch64 modules
make[2]: Entering directory `/usr/src/kernels/4.14.0-115.13.1.1chaos.el7a.aarch64'
Makefile:643: arch/aarch64/Makefile: No such file or directory
make[2]: *** No rule to make target `arch/aarch64/Makefile'.
make[2]: Failed to remake makefile `arch/aarch64/Makefile'.
  CC [M]  /tmp/build/ihk/linux/core/host_driver.o
In file included from /tmp/ihk/../ihk/linux/core/host_driver.c:19:0:
./include/linux/sched.h:12:25: fatal error: asm/current.h: No such file or directory
 #include <asm/current.h>
                         ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/linux/core/host_driver.o] Error 1
  CC [M]  /tmp/build/ihk/linux/core/mem_alloc.o
In file included from ./include/linux/compiler.h:258:0,
                 from ./include/linux/linkage.h:5,
                 from ./include/linux/kernel.h:7,
                 from /tmp/ihk/../ihk/linux/core/mem_alloc.c:10:
./include/uapi/linux/types.h:5:23: fatal error: asm/types.h: No such file or directory
 #include <asm/types.h>
                       ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/linux/core/mem_alloc.o] Error 1
  CC [M]  /tmp/build/ihk/linux/core/mm.o
In file included from ./include/linux/compiler.h:258:0,
                 from ./include/linux/linkage.h:5,
                 from ./include/linux/kernel.h:7,
                 from /tmp/ihk/../ihk/linux/core/mm.c:9:
./include/uapi/linux/types.h:5:23: fatal error: asm/types.h: No such file or directory
 #include <asm/types.h>
                       ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/linux/core/mm.o] Error 1
  CC [M]  /tmp/build/ihk/linux/core/mikc.o
In file included from /tmp/ihk/../ihk/linux/core/mikc.c:12:0:
./include/linux/sched.h:12:25: fatal error: asm/current.h: No such file or directory
 #include <asm/current.h>
                         ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/linux/core/mikc.o] Error 1
  CC [M]  /tmp/build/ihk/linux/core/../../ikc/linux.o
In file included from ./include/linux/compiler.h:258:0,
                 from ./include/linux/linkage.h:5,
                 from ./include/linux/kernel.h:7,
                 from /tmp/ihk/../ihk/linux/core/../../ikc/include/ikc/ihk.h:48,
                 from /tmp/ihk/../ihk/linux/core/../../ikc/linux.c:8:
./include/uapi/linux/types.h:5:23: fatal error: asm/types.h: No such file or directory
 #include <asm/types.h>
                       ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/linux/core/../../ikc/linux.o] Error 1
  CC [M]  /tmp/build/ihk/linux/core/../../ikc/master.o
In file included from ./include/linux/compiler.h:258:0,
                 from ./include/linux/linkage.h:5,
                 from ./include/linux/kernel.h:7,
                 from /tmp/ihk/../ihk/linux/core/../../ikc/include/ikc/ihk.h:48,
                 from /tmp/ihk/../ihk/linux/core/../../ikc/master.c:7:
./include/uapi/linux/types.h:5:23: fatal error: asm/types.h: No such file or directory
 #include <asm/types.h>
                       ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/linux/core/../../ikc/master.o] Error 1
  CC [M]  /tmp/build/ihk/linux/core/../../ikc/queue.o
In file included from ./include/linux/compiler.h:258:0,
                 from ./include/linux/linkage.h:5,
                 from ./include/linux/kernel.h:7,
                 from /tmp/ihk/../ihk/linux/core/../../ikc/include/ikc/ihk.h:48,
                 from /tmp/ihk/../ihk/linux/core/../../ikc/queue.c:8:
./include/uapi/linux/types.h:5:23: fatal error: asm/types.h: No such file or directory
 #include <asm/types.h>
                       ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/linux/core/../../ikc/queue.o] Error 1
make[3]: Target `__build' not remade because of errors.
make[2]: *** [_module_/tmp/build/ihk/linux/core] Error 2
make[2]: Target `modules' not remade because of errors.
make[2]: Leaving directory `/usr/src/kernels/4.14.0-115.13.1.1chaos.el7a.aarch64'
make[1]: *** [modules] Error 2
make[1]: Leaving directory `/tmp/build/ihk/linux/core'
make: *** [core-modules] Error 2
make[1]: Entering directory `/tmp/build/ihk/linux/user'
gcc -g -Wall -O -I/tmp/ihk/../ihk/linux/user/../../linux/include/ -I/tmp/ihk/../ihk/linux/user/../../linux/include/ihk/arch/aarch64 -I/tmp/build/ihk/linux/user -I/tmp/build/ihk/linux/user/../include/ -I/tmp/build/ihk/linux/user/../../ -fPIC -o ihklib.o -c /tmp/ihk/../ihk/linux/user/ihklib.c
/tmp/ihk/../ihk/linux/user/ihklib.c:32:33: fatal error: ihk/ihk_arch_rusage.h: No such file or directory
 #include <ihk/ihk_arch_rusage.h>
                                 ^
compilation terminated.
make[1]: *** [ihklib.o] Error 1
gcc -g -Wall -O -I/tmp/ihk/../ihk/linux/user/../../linux/include/ -I/tmp/ihk/../ihk/linux/user/../../linux/include/ihk/arch/aarch64 -I/tmp/build/ihk/linux/user -I/tmp/build/ihk/linux/user/../include/ -I/tmp/build/ihk/linux/user/../../ -o maccess /tmp/ihk/../ihk/linux/user/maccess.c -lbfd -liberty 
/tmp/ihk/../ihk/linux/user/maccess.c:4:23: fatal error: ihk/rdtsc.h: No such file or directory
 #include <ihk/rdtsc.h>
                       ^
compilation terminated.
make[1]: *** [maccess] Error 1
make[1]: Target `all' not remade because of errors.
make[1]: Leaving directory `/tmp/build/ihk/linux/user'
make: *** [user] Error 2
make: Target `all' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1