Update patch set 8
Patch Set 8: Verified-1

build failed:
[ 10%] Generating kmod_always_rebuild
[ 20%] Building kmod ihk
[ 30%] Built target ihk_ko
[ 40%] Building C object linux/user/CMakeFiles/ihklib.dir/ihklib.c.o
/work/mcktest/git/ihk/linux/user/ihklib.c: In function ‘ihk_os_assign_mem’:
/work/mcktest/git/ihk/linux/user/ihklib.c:2109:7: error: unused variable ‘errno_save’ [-Werror=unused-variable]
   int errno_save = errno;
       ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2782:12: error: invalid storage class for function ‘get_meminfo_path’
 static int get_meminfo_path(char *path, int os_index, int node)
            ^
/work/mcktest/git/ihk/linux/user/ihklib.c:2861:12: error: invalid storage class for function ‘ihklib_os_query_mem’
 static int ihklib_os_query_mem(int index, unsigned long *result,
            ^
/work/mcktest/git/ihk/linux/user/ihklib.c:3523:1: error: expected declaration or statement at end of input
 }
 ^
/work/mcktest/git/ihk/linux/user/ihklib.c:3523:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
make[2]: *** [linux/user/CMakeFiles/ihklib.dir/ihklib.c.o] Error 1
make[2]: Target `linux/user/CMakeFiles/ihklib.dir/build' not remade because of errors.
make[1]: *** [linux/user/CMakeFiles/ihklib.dir/all] Error 2
[ 50%] Generating kmod_always_rebuild
[ 60%] Building kmod ihk-smp-x86_64
[ 70%] Built target ihk-smp-x86_64_ko
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 8
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1